### ISSUE TITLE
Zoneinfo failing to compile (breaks subsequent termcap installation)

### ISSUE THREAD

**Issue by majenkotech** [sergev/LiteBSD#42]
Zoneinfo is failing to compile - missing sys/types.h.  As a result "bmake install" on share fails which means /usr/share/misc/termcap (etc) are not installed.

    ===> zoneinfo
    gcc -m32 -O -DTM_GMTOFF=tm_gmtoff -DTM_ZONE=tm_zone -Werror -c zic.c
    zic.c:45:23: fatal error: sys/types.h: No such file or directory
     #include <sys/types.h>
                           ^
    compilation terminated.
    *** Error code 1

**Comment by majenkotech** [comment]
Ah, it's a local compilation not a target compilation - and it's forced to 32-bit. (-m32) - I guess I need some 32-bit headers in there then...?

**Comment by majenkotech** [comment]
Requires installation of: 

* libc6-dev:i386
* lib32gcc-4.9-dev:

**Comment by sergev** [comment]
It makes sense to fix zoneinfo to work on amd64 architecture as well - someday.
For now it just needs a properly installed i386 development libraries and includes.
