### ISSUE TITLE
as(1) instructions to work with pcc(1) (and lcc)

### ISSUE THREAD

**Issue by ibara** [sergev/LiteBSD#58]
`as(1)` doesn't seem to support the following pseudo-instructions, which `pcc(1)` emits:
`.p2align`
`sw $fp, ($sp)` syntax: `sw $fp, 4($sp)` works but `sw $fp, ($sp)` does not.
`.extern` (lcc emits this)

**Comment by sergev** [comment]
First two issues have being fixed in fcb1a490ce8b5bbe28b4410618d438937b9a222b.
As for .extern directive, it is not available in GNU as well. I would propose to modify lcc to use ".comm name, size" instead.

**Comment by ibara** [comment]
Can do. Thanks Serge!

**Comment by sergev** [comment]
You are welcome!
Frankly, the assembler (and linker) is not yet complete - currently the HI16 relocation type can generate wrong result. I'm still working on it.

**Comment by ibara** [comment]
Hmm... according to the latest GNU as documentation, .extern should be supported: https://sourceware.org/binutils/docs-2.26/as/MIPS-Small-Data.html#MIPS-Small-Data

**Comment by sergev** [comment]
".extern is accepted in the source program—for compatibility with other assemblers—but it is ignored. as treats all undefined symbols as external."

It's a quote from the same document: https://sourceware.org/binutils/docs-2.26/as/Extern.html

**Comment by ibara** [comment]
Ah, ok. Good stuff then!

**Comment by ibara** [comment]
Closing this as you added support for .p2align and empty offset in load/store instructions, and I modified lcc to not emit .extern (and .sdata while I was there since it seems like your as doesn't support it either, which I think is fine).
